[[site.patch.ntpd.files]]
dst = "/etc/ntpd.conf"
lines = [
  "server 169.254.169.123 weight 2", # https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/
  "servers pool.ntp.org",
  "sensor *",
  "constraints from openbsd.org",
]
