name: Sanity checks
on: push

jobs:
  sanity-example:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: The example's specification is clean
      run: scripts/is-clean example/openbsd.toml

  sanity-script:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.18.4
    steps:
    - name: Install essentials
      run: apk add python3

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Script is footloose and fancy-free
      run: scripts/load_module.py openbsd
