name: Tests
on:
  schedule:
    - cron: "* * 7 * *"
  workflow_run:
    workflows: [ Sanity checks ]
    types: [ completed ]
    branches: [ main ]

jobs:
  deps:
    strategy:
      matrix:
        distro: [ "alpine:latest", "ubuntu:latest", "debian:latest", "archlinux:latest" ]
        arch: [ amd64, i386 ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.distro }}
    steps:
    - name: Install essentials
      run: apk add python3

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: ./openbsd deps --install --arch=${{ matrix.arch }}

  base:
    needs:
      - deps
    strategy:
      matrix:
        version: [ 7.3, 7.4 ]
        arch: [ amd64, i386 ]
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    env:
      OPENBSD_CACHE: /tmp/cache
      WORKDIR: /${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
    steps:
    - name: Install essentials
      run: apk add bash python3 tar

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: ./openbsd deps --install --arch=${{ matrix.arch }}

    - name: Cache OpenBSD files
      id: cache-openbsd
      uses: actions/cache@v3
      with:
          path: ${{ env.OPENBSD_CACHE }}
          key: openbsd-${{ matrix.version }}-${{ matrix.arch }}-${{ github.job }}
          restore-keys: |
              openbsd-${{ matrix.version }}-${{ matrix.arch }}-${{ github.job }}
              openbsd-${{ matrix.version }}-${{ matrix.arch }}
              openbsd-${{ matrix.version }}
              openbsd

    - name: Run test
      run: tests/base -v ${{ matrix.version }} -a ${{ matrix.arch }}

    - name: Keep artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ github.job }}-${{ matrix.version }}-${{ matrix.arch }}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
        retention-days: 3
        path: /${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}/**/*

  example:
    needs:
      - base
    strategy:
      matrix:
        version: [ 7.4 ]
        arch: [ amd64 ]
    runs-on: ubuntu-latest
    env:
      OPENBSD_CACHE: /tmp/cache
      WORKDIR: /${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
    container:
      image: alpine:latest

    steps:
    - name: Install essentials
      run: apk add bash python3 tar

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: ./openbsd deps --install --arch=${{ matrix.arch }}

    - name: Cache OpenBSD files
      id: cache-openbsd
      uses: actions/cache@v3
      with:
          path: ${{ env.OPENBSD_CACHE }}
          key: openbsd-${{ matrix.version }}-${{ matrix.arch }}-${{ github.job }}
          restore-keys: |
              openbsd-${{ matrix.version }}-${{ matrix.arch }}-${{ github.job }}
              openbsd-${{ matrix.version }}-${{ matrix.arch }}
              openbsd-${{ matrix.version }}
              openbsd

    - name: Run test
      run: tests/example -v ${{ matrix.version }} -a ${{ matrix.arch }}

    - name: Keep artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ github.job }}-${{ matrix.version }}-${{ matrix.arch }}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
        retention-days: 3
        path: /${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}/**/*
